const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { validateFile, decodeEmail, sha256, safeName } = require('../src/services/purchaseEmailProofService');

const emlFile = (content, overrides = {}) => { const buffer = Buffer.from(content); return { buffer, size: buffer.length, originalname: 'proof.eml', mimetype: 'message/rfc822', ...overrides }; };
const plain = `From: Client User <client@example.com>\r\nTo: CRM <crm@example.com>\r\nSubject: Purchase confirmation\r\nMessage-ID: <purchase-1@example.com>\r\nDate: Wed, 20 Aug 2026 10:30:00 +0530\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\nPurchase data is confirmed.`;

test('detects a valid EML using extension, MIME and RFC822 headers', () => assert.equal(validateFile(emlFile(plain)), 'eml'));
test('rejects a non-email renamed to EML', () => assert.throws(() => validateFile(emlFile('not really an email')), /does not match/));
test('rejects an unsupported file renamed to MSG without OLE signature', () => assert.throws(() => validateFile(emlFile(plain, { originalname: 'fake.msg', mimetype: 'application/vnd.ms-outlook' })), /does not match/));
test('recognizes the Outlook compound-file signature', () => { const buffer = Buffer.concat([Buffer.from([0xd0,0xcf,0x11,0xe0,0xa1,0xb1,0x1a,0xe1]), Buffer.alloc(64)]); assert.equal(validateFile({ buffer, size: buffer.length, originalname: 'proof.msg', mimetype: 'application/vnd.ms-outlook' }), 'msg'); });
test('plain-text EML decodes normalized headers and body', async () => { const decoded = await decodeEmail(emlFile(plain), 'eml'); assert.equal(decoded.subject, 'Purchase confirmation'); assert.equal(decoded.from.email, 'client@example.com'); assert.match(decoded.textBody, /confirmed/); assert.equal(decoded.decodeStatus, 'Decoded'); });
test('HTML EML is sanitized and never preserves scripts, forms, iframes or remote images', async () => { const html = `From: x@example.com\r\nTo: y@example.com\r\nSubject: HTML proof\r\nDate: Wed, 20 Aug 2026 10:30:00 +0530\r\nMIME-Version: 1.0\r\nContent-Type: text/html\r\n\r\n<p onclick="evil()">Safe</p><script>evil()</script><iframe src="x"></iframe><form></form><img src="https://tracker.test/pixel">`; const decoded = await decodeEmail(emlFile(html), 'eml'); assert.match(decoded.sanitizedHtmlBody, /Safe/); assert.doesNotMatch(decoded.sanitizedHtmlBody, /script|iframe|form|img|onclick|tracker/i); });
test('multipart EML decodes text and an attachment', async () => { const multipart = `From: x@example.com\r\nTo: y@example.com\r\nSubject: Attached\r\nDate: Wed, 20 Aug 2026 10:30:00 +0530\r\nMIME-Version: 1.0\r\nContent-Type: multipart/mixed; boundary=abc\r\n\r\n--abc\r\nContent-Type: text/plain\r\n\r\nSee attachment.\r\n--abc\r\nContent-Type: application/pdf; name="proof.pdf"\r\nContent-Disposition: attachment; filename="proof.pdf"\r\nContent-Transfer-Encoding: base64\r\n\r\nJVBERi0xLjQ=\r\n--abc--`; const decoded = await decodeEmail(emlFile(multipart), 'eml'); assert.equal(decoded.attachments.length, 1); assert.equal(decoded.attachments[0].fileName, 'proof.pdf'); });
test('missing sender creates Failed decode status and is not valid proof', async () => { const value = plain.replace('From: Client User <client@example.com>\r\n', ''); const decoded = await decodeEmail(emlFile(value), 'eml'); assert.equal(decoded.decodeStatus, 'Failed'); assert.ok(decoded.decodeWarnings.some((warning) => /Sender/.test(warning))); });
test('same input produces a stable SHA-256 checksum', () => assert.equal(sha256(Buffer.from('same')), sha256(Buffer.from('same'))));
test('unsafe attachment filenames are reduced to a safe basename', () => { assert.equal(safeName('../../secret<script>.pdf').includes('/'), false); assert.equal(safeName('../../secret<script>.pdf').includes('<'), false); });
test('backend routes require authentication for upload, preview, download and delete', () => { const clients = fs.readFileSync(path.resolve(__dirname, '../src/routes/clients.js'), 'utf8'); const proofs = fs.readFileSync(path.resolve(__dirname, '../src/routes/purchaseProofs.js'), 'utf8'); assert.match(clients, /purchase-proof\/email', requireAuth/); assert.equal((proofs.match(/router\.(get|delete)\([^\n]+requireAuth/g) || []).length, 4); });
test('email proof schema isolates records by client, year, row and checksum', () => { const model = fs.readFileSync(path.resolve(__dirname, '../src/models/PurchaseProof.js'), 'utf8'); assert.match(model, /clientId: 1, financialYear: 1, progressParticular: 1, checksum: 1/); assert.match(model, /unique: true/); });
test('failed decode is persisted but never appended as valid checklist proof', () => { const controller = fs.readFileSync(path.resolve(__dirname, '../src/controllers/purchaseProofController.js'), 'utf8'); const failed = controller.indexOf("emailData.decodeStatus === 'Failed'"); const append = controller.indexOf('record.checklist ='); assert.ok(failed > 0 && append > failed); });
test('decoded HTML is never rendered with dangerouslySetInnerHTML', () => { const viewer = fs.readFileSync(path.resolve(__dirname, '../../frontend/src/features/clientMaster/OutlookMsgViewer.jsx'), 'utf8'); assert.doesNotMatch(viewer, /dangerouslySetInnerHTML/); assert.match(viewer, /scripts and remote images are never rendered/); });
test('frontend exposes Email, Attachments, Headers and File Information tabs', () => { const viewer = fs.readFileSync(path.resolve(__dirname, '../../frontend/src/features/clientMaster/OutlookMsgViewer.jsx'), 'utf8'); ['Email', 'Attachments', 'Headers', 'File Information'].forEach((label) => assert.match(viewer, new RegExp(label))); });
