const mongoose = require('mongoose');

const LeadSchema = new mongoose.Schema({
  leadCode: { type: String, trim: true, unique: true, sparse: true },
  sourceLeadId: { type: String, trim: true },
  externalLeadId: { type: String, trim: true, index: true },
  companyIdentity: { type: String, trim: true, index: true },
  communicationMode: { type: String, trim: true },
  communicationModeNote: { type: String, trim: true },
  status: { type: String, trim: true },
  company: { type: String, trim: true },
  industryType: { type: String, trim: true },
  eprCategory: { type: String, trim: true },
  piboParent: { type: String, enum: ['PIBO', 'SIMP', 'PWP'], trim: true },
  piboCategoryParent: { type: String, enum: ['PIBO', 'SIMP', 'PWP'], trim: true },
  // Canonical name for the selected PIBO/SIMP/PWP child. Legacy records may
  // still contain piboCategory and are normalized by the lead controller.
  subApplicantType: { type: String, trim: true },
  applicantType: { type: String, trim: true },
  serviceSelections: { type: Array, default: [] },
  servicesOffered: { type: String, trim: true },
  firstAnnualReturnYearApplicable: { type: String, trim: true },
  addresses: { type: Array, default: [] },
  contacts: { type: Array, default: [] },
  assignments: { type: Array, default: [] },
  addressLine1: { type: String, trim: true },
  addressLine2: { type: String, trim: true },
  addressLine3: { type: String, trim: true },
  landmark: { type: String, trim: true },
  state: { type: String, trim: true },
  city: { type: String, trim: true },
  pinCode: { type: String, trim: true, match: [/^(?:\d{6})?$/, 'PIN code must contain exactly 6 digits'] },
  existingClient: { type: String, enum: ['Yes', 'No'], default: 'No' },
  website: { type: String, trim: true },
  salutation: { type: String, trim: true },
  contactPerson: { type: String, trim: true },
  designation: { type: String, trim: true },
  emails: { type: String, trim: true },
  emailsSentCount: { type: Number, default: 0 },
  lastEmailSent: { type: String, trim: true },
  introductionEmailSentAt: { type: Date },
  introductionEmailVersion: { type: Number, default: 0 },
  introductionEmailLastRequestedAt: { type: Date },
  introductionEmailLastStatus: { type: String, enum: ['sent', 'skipped', 'failed'], trim: true },
  introductionEmailLastError: { type: String, trim: true },
  mobileNo1: { type: String, trim: true },
  mobileNo2: { type: String, trim: true },
  whatsappNo: { type: String, trim: true },
  linkedinUrl: { type: String, trim: true },
  businessCardUrl: { type: String },
  referredBy: { type: String, trim: true },
  source: { type: String, trim: true },
  notes: { type: String, trim: true },
  assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  assignedToText: { type: String, trim: true },
  assignedStaff: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  assignedStaffText: { type: String, trim: true },
  assignedStaffEmail: { type: String, trim: true, lowercase: true },
  assignedBy: { type: String, trim: true },
  importedCreatedBy: { type: String, trim: true },
  createdByCrmUserId: { type: String, trim: true, index: true },
  createdByName: { type: String, trim: true },
  createdByEmail: { type: String, trim: true, lowercase: true },
  creatorChangeHistory: { type: Array, default: [] },
  generatedForUser: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
  generatedForName: { type: String, trim: true },
  generatedForEmail: { type: String, trim: true, lowercase: true },
  creationMode: { type: String, enum: ['self', 'other'], default: 'self' },
  createdOnBehalfOfUser: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  createdOnBehalfOfName: { type: String, trim: true },
  createdOnBehalfOfEmail: { type: String, trim: true, lowercase: true },
  updatedBy: { type: String, trim: true },
  closedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  closedByText: { type: String, trim: true },
  closedByEmail: { type: String, trim: true, lowercase: true },
  closedOnBehalfOfUser: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  closedOnBehalfOfName: { type: String, trim: true },
  closedOnBehalfOfEmail: { type: String, trim: true, lowercase: true },
  closedAt: { type: Date },
  leadDate: { type: String, trim: true },
  nextFollowUpDate: { type: String, trim: true },
  nextFollowUpTime: { type: String, trim: true },
  followUpRemarks: { type: String, trim: true },
  followUpPriority: { type: String, trim: true, default: 'Medium' },
  followUpFlag: { type: String, trim: true },
  followUpHistory: { type: Array, default: [] },
  importedCreatedAt: { type: String, trim: true },
  importedUpdatedAt: { type: String, trim: true },
  recordStatus: { type: String, trim: true, default: 'ACTIVE' },
  complianceHealthReport: { type: mongoose.Schema.Types.Mixed },
  workflowStatus: { type: String, enum: ['draft', 'submitted'], default: 'draft' },
  formStartedAt: { type: Date },
  assignReachedAt: { type: Date },
  submittedAt: { type: Date },
  fillDurationSeconds: { type: Number, min: 0 },
  bulkImported: { type: Boolean, default: false, index: true },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  sync: {
    source: { type: String, trim: true, default: 'crm' },
    status: { type: String, enum: ['synced', 'pending', 'failed'], default: 'synced', index: true },
    lastSyncedAt: { type: Date },
    lastError: { type: String, trim: true }
  }
}, { timestamps: true });

LeadSchema.index({ companyIdentity: 1, workflowStatus: 1 });

module.exports = mongoose.model('Lead', LeadSchema);
