const express = require('express');
const multer = require('multer');
const router = express.Router();
const clientCtrl = require('../controllers/clientController');
const reviewCtrl = require('../controllers/clientComplianceReviewController');
const purchaseCtrl = require('../controllers/purchaseDataController');
const salesCtrl = require('../controllers/salesDataController');
const purchaseProofCtrl = require('../controllers/purchaseProofController');
const { requireAuth, requireRoles } = require('../middleware/auth');
const { ADMIN_ROLES, CLIENT_APPROVAL_ROLES } = require('../constants/roles');
const emailProofUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: Math.max(1, Number(process.env.EMAIL_PROOF_MAX_SIZE_MB) || 15) * 1024 * 1024, files: 1, fields: 10 } }).single('file');
const receiveEmailProof = (req, res, next) => emailProofUpload(req, res, (error) => error ? res.status(error.code === 'LIMIT_FILE_SIZE' ? 413 : 400).json({ success: false, message: error.code === 'LIMIT_FILE_SIZE' ? 'Email proof exceeds the configured size limit.' : 'Invalid email proof upload.', code: error.code || 'MULTIPART_UPLOAD_FAILED' }) : next());

router.get('/', requireAuth, clientCtrl.listClients);
router.get('/discovery/search', requireAuth, clientCtrl.searchClientMasterCompanies);
router.get('/discovery/services', requireAuth, clientCtrl.listClientMasterServices);
router.get('/discovery/catalog', requireAuth, clientCtrl.listClientMasterCatalog);
router.get('/pending-approvals', requireAuth, clientCtrl.listPendingApprovals);
router.patch('/pending-approvals/clients/approve-all', requireAuth, requireRoles(CLIENT_APPROVAL_ROLES), clientCtrl.approveAllPendingClients);
router.post('/bulk', requireAuth, requireRoles(ADMIN_ROLES), clientCtrl.bulkCreateClients);
router.post('/years/bulk', requireAuth, requireRoles(ADMIN_ROLES), clientCtrl.bulkUpdateClientYears);
router.post('/onboarding/cpcb', requireAuth, clientCtrl.updateCpcbOnboarding);
router.post('/', requireAuth, clientCtrl.createClient);
router.get('/:id', requireAuth, clientCtrl.getClient);
router.get('/:id/annual-return/po-status', requireAuth, clientCtrl.getAnnualReturnPoStatus);
router.post('/:clientId/purchase-proof/email', requireAuth, receiveEmailProof, purchaseProofCtrl.uploadEmailProof);
router.get('/:id/purchase-data', requireAuth, purchaseCtrl.getPurchaseData);
router.put('/:id/purchase-data/checklist', requireAuth, purchaseCtrl.updateChecklist);
router.put('/:id/purchase-data/screenshots', requireAuth, purchaseCtrl.updateScreenshots);
router.post('/:id/purchase-imports/:source', requireAuth, purchaseCtrl.importPurchaseRows);
router.delete('/:id/purchase-imports/:source', requireAuth, purchaseCtrl.removePurchaseImport);
router.get('/:id/purchase-data/rows', requireAuth, purchaseCtrl.listPurchaseRows);
router.get('/:id/purchase-reconciliation', requireAuth, purchaseCtrl.getReconciliation);
router.get('/:id/purchase-imports/:source/errors', requireAuth, purchaseCtrl.getPurchaseErrors);
router.post('/:id/purchase-data/submit', requireAuth, purchaseCtrl.submitPurchaseData);
router.post('/:id/purchase-data/manager-review', requireAuth, purchaseCtrl.managerReview);
router.post('/:id/purchase-data/compliance-review', requireAuth, purchaseCtrl.complianceReview);
router.get('/:id/sales-data', requireAuth, salesCtrl.getSalesData);
router.put('/:id/sales-data/checklist', requireAuth, salesCtrl.updateChecklist);
router.put('/:id/sales-data/screenshots', requireAuth, salesCtrl.updateScreenshots);
router.post('/:id/sales-imports/:source', requireAuth, salesCtrl.importSalesRows);
router.delete('/:id/sales-imports/:source', requireAuth, salesCtrl.removeSalesImport);
router.get('/:id/sales-data/rows', requireAuth, salesCtrl.listSalesRows);
router.get('/:id/sales-reconciliation', requireAuth, salesCtrl.getReconciliation);
router.post('/:id/sales-data/submit', requireAuth, salesCtrl.submitSalesData);
router.post('/:id/sales-data/manager-review', requireAuth, salesCtrl.managerReview);
router.post('/:id/sales-data/compliance-review', requireAuth, salesCtrl.complianceReview);
router.get('/:id/compliance-review', requireAuth, requireRoles(CLIENT_APPROVAL_ROLES), reviewCtrl.getReview);
router.put('/:id/compliance-review/sections/:sectionKey', requireAuth, requireRoles(CLIENT_APPROVAL_ROLES), reviewCtrl.updateSection);
router.post('/:id/compliance-review/decision', requireAuth, requireRoles(CLIENT_APPROVAL_ROLES), reviewCtrl.completeReview);
router.patch('/:id/approval', requireAuth, requireRoles(CLIENT_APPROVAL_ROLES), clientCtrl.updateClientApproval);
router.put('/:id/allocations', requireAuth, requireRoles([...ADMIN_ROLES, 'manager']), clientCtrl.upsertClientServiceAllocations);
router.put('/:id/annual-return', requireAuth, clientCtrl.updateAnnualReturn);
router.put('/:id', requireAuth, clientCtrl.updateClient);

module.exports = router;
