const express = require('express');
const router = express.Router();
const leadCtrl = require('../controllers/leadController');
const { requireAuth, requireRoles } = require('../middleware/auth');
const { ADMIN_ROLES } = require('../constants/roles');
const quotationCtrl = require('../controllers/quotationController');
const temporaryAssignmentCtrl = require('../controllers/temporaryLeadAssignmentController');
const temporaryLeadCtrl = require('../controllers/temporaryLeadController');

router.get('/', requireAuth, leadCtrl.listLeads);
router.get('/service-catalog', requireAuth, leadCtrl.listServiceCatalog);
router.get('/dropdown-options', requireAuth, leadCtrl.listLeadDropdownOptions);
router.post('/dropdown-options', requireAuth, requireRoles(ADMIN_ROLES), leadCtrl.createLeadDropdownOption);
router.post('/service-catalog/categories', requireAuth, requireRoles(ADMIN_ROLES), leadCtrl.createServiceCatalogCategory);
router.post('/service-catalog/categories/:category/services', requireAuth, requireRoles(ADMIN_ROLES), leadCtrl.addServiceCatalogOffering);
router.get('/search/company', requireAuth, leadCtrl.searchCompanies);
router.get('/duplicate-approvals', requireAuth, leadCtrl.listDuplicateLeadApprovals);
router.get('/temporary', requireAuth, temporaryLeadCtrl.list);
router.post('/temporary', requireAuth, temporaryLeadCtrl.create);
router.post('/temporary/:id/convert', requireAuth, temporaryLeadCtrl.convert);
router.post('/temporary/:id/follow-up', requireAuth, temporaryLeadCtrl.saveFollowUp);
router.post('/temporary/:id/follow-up/close', requireAuth, temporaryLeadCtrl.closeFollowUp);
router.post('/duplicate-approvals', requireAuth, leadCtrl.requestDuplicateLeadApproval);
router.patch('/duplicate-approvals/:id', requireAuth, leadCtrl.updateDuplicateLeadApproval);
router.post('/bulk', requireAuth, requireRoles(ADMIN_ROLES), leadCtrl.bulkCreateLeads);
router.post('/', requireAuth, leadCtrl.createLead);
router.patch('/:id/allocation', requireAuth, requireRoles(ADMIN_ROLES), leadCtrl.allocateLead);
router.patch('/:id/creator', requireAuth, requireRoles(ADMIN_ROLES), leadCtrl.updateLeadCreator);
router.get('/:id/history', requireAuth, leadCtrl.getLeadHistory);
router.post('/:id/history/email', requireAuth, leadCtrl.recordIntroductionEmail);
router.post('/:id/royalty-claims', requireAuth, leadCtrl.claimLeadRoyalty);
router.post('/:id/temporary-assignments', requireAuth, temporaryAssignmentCtrl.requestTemporaryAssignment);
router.patch('/temporary-assignments/:approvalId', requireAuth, temporaryAssignmentCtrl.decideTemporaryAssignment);
router.patch('/purchase-order-approvals/:id', requireAuth, requireRoles(ADMIN_ROLES), leadCtrl.decidePurchaseOrderApproval);
router.patch('/purchase-order-approvals/:id/proof', requireAuth, requireRoles(ADMIN_ROLES), leadCtrl.uploadPurchaseOrderProof);
router.get('/:leadId/quotations', requireAuth, quotationCtrl.listLeadQuotations);
router.put('/:id', requireAuth, leadCtrl.updateLead);

module.exports = router;
