export const QUOTATION_SCOPE_PRESET_OPTIONS = Object.freeze([
  { key: 'basic', label: 'Basic' },
  { key: 'premium', label: 'Premium' },
  { key: 'superPremium', label: 'Super Premium' }
]);

export const QUOTATION_SCOPE_PRESETS = Object.freeze({
  basic: Object.freeze([
    'Compliance Health Check Report: 1.1 Initial Compliance Assessment & Application Type Evaluation to understand basic compliance gaps',
    'Services: 2.1 Key Account Manager Assigned',
    'Services: 2.5 Annual Return Filing',
    'Services: 2.6 Common SSO Portal Support',
    'Data Analysis: 3.1 Basic Document Assessment (New Application)',
    'Data Analysis: 3.4 Plastic Category Classification*',
    'Data Analysis: 3.5 Polymer Type Identification',
    'Data Analysis: 3.6 Container Type Mapping',
    'Data Analysis: 3.7 HSN Code Data Management',
    'Data Management: 4.1 Purchase & Sales Data',
    'Data Management: 4.2 Export / Import Data Verification',
    'Data Management: 4.3 HSN Code Data Management',
    'Data Management: 4.4 Internal Transactions Traceability Assessment',
    'Data Upload & Processing: 5.4 Pre Consumer Data Uploading',
    'Data Upload & Processing: 5.5 Post Consumer Data Uploading',
    'Packaging Material Compliance: 7.1 Basic Category Wise Packaging Assessment*',
    'Packaging Material Compliance: 7.2 Guidance on Primary, Secondary & Tertiary Packaging Identification',
    'Regulatory Compliance: 8.1 Policy Notification / Circulars Decoding',
    'Credit / Obligation Management: 9.1 EPR Target Calculation (Applicable, Actual, Unfulfilled, Minimum Carry Forward)',
    'Credit / Obligation Management: 9.3 Credit Management (Flag Credits, Verified Credits & Credit Offset)',
    'Credit / Obligation Management: 9.5 Credit Procurement Support',
    'Training & Awareness: 10.1 Formal Explanation of Scope & Deliverables',
    'Training & Awareness: 10.2 Standard Webinars & Knowledge Sessions',
    'Training & Awareness: 10.7 CPCB Updates',
    'Training & Awareness: 10.8 Common EPR Portal (CEPR) Introduction covering Portal Structure & Navigation, Workflow & Process Overview, Data Reporting & Verification, Key Features & Enhancements, and Applicability & Compliance Awareness Session',
    'CTO / CTE Assessment: 12.1 Consent to Establish (CTE) Applicability Assessment',
    'CTO / CTE Assessment: 12.2 Consent to Operate (CTO) Applicability Assessment',
    'CTO / CTE Assessment: 12.5 Consent Validity Review'
  ]),
  premium: Object.freeze([
    'Compliance Health Check Report: 1.1 Initial Compliance Assessment & Application Type Evaluation to understand basic compliance gaps',
    'Services: 2.1 Key Account Manager Assigned',
    'Services: 2.2 Compliance Manager Assigned',
    'Services: 2.4 On-call Support',
    'Services: 2.5 Annual Return Filing',
    'Services: 2.6 Common SSO Portal Support',
    'Data Analysis: 3.1 Basic Document Assessment (New Application)',
    'Data Analysis: 3.4 Plastic Category Classification*',
    'Data Analysis: 3.5 Polymer Type Identification',
    'Data Analysis: 3.6 Container Type Mapping',
    'Data Analysis: 3.7 HSN Code Data Management',
    'Data Management: 4.1 Purchase & Sales Data',
    'Data Management: 4.2 Export / Import Data Verification',
    'Data Management: 4.3 HSN Code Data Management',
    'Data Management: 4.4 Internal Transactions Traceability Assessment',
    'Data Upload & Processing: 5.1 Data Cleaning',
    'Data Upload & Processing: 5.2 Data Formatting',
    'Data Upload & Processing: 5.3 Invoice Mapping',
    'Data Upload & Processing: 5.4 Pre Consumer Data Uploading',
    'Data Upload & Processing: 5.5 Post Consumer Data Uploading',
    'Supplier / Buyer Compliance Management: 6.1 Registered Supplier / Buyer Verification',
    'Supplier / Buyer Compliance Management: 6.2 Unregistered Supplier / Buyer Verification',
    'Supplier / Buyer Compliance Management: 6.3 Recycled Content (PCR) Compliance Guidance & Supplier Confirmation',
    'Supplier / Buyer Compliance Management: 6.4 Supplier / Buyer Training and Awareness',
    'Packaging Material Compliance: 7.1 Basic Category Wise Packaging Assessment*',
    'Packaging Material Compliance: 7.2 Guidance on Primary, Secondary & Tertiary Packaging Identification',
    'Packaging Material Compliance: 7.3 PCR Compliance',
    'Packaging Material Compliance: 7.4 Reuse Compliance (As Applicable)',
    'Packaging Material Compliance: 7.5 Marking & Labelling Compliance',
    'Packaging Material Compliance: 7.6 Packaging Assessment Report',
    'Regulatory Compliance: 8.1 Policy Notification / Circulars Decoding',
    'Regulatory Compliance: 8.2 Personalised Company-level Decoding',
    'Regulatory Compliance: 8.4 Show Cause Notice Reply (Up to 2 Notices)',
    'Regulatory Compliance: 8.7 Statutory PCR Exemption Support (If Applicable)',
    'Regulatory Compliance: 8.8 Statutory Reuse Exemption Support (If Applicable)',
    'Credit / Obligation Management: 9.1 EPR Target Calculation (Applicable, Actual, Unfulfilled, Minimum Carry Forward)',
    'Credit / Obligation Management: 9.2 Exemption Applicability Check',
    'Credit / Obligation Management: 9.3 Credit Management (Flag Credits, Verified Credits & Credit Offset)',
    'Credit / Obligation Management: 9.4 Carry Forward Eligibility Assessment',
    'Credit / Obligation Management: 9.5 Credit Procurement Support',
    'Credit / Obligation Management: 9.6 Credit Traceability Documentation Compliance',
    'Training & Awareness: 10.1 Formal Explanation of Scope & Deliverables',
    'Training & Awareness: 10.2 Standard Webinars & Knowledge Sessions',
    'Training & Awareness: 10.3 Personalised Webinar & Knowledge Sessions (2 Sessions)',
    'Training & Awareness: 10.4 Multi-department Awareness & Training',
    'Training & Awareness: 10.6 Compliance Awareness Sessions',
    'Training & Awareness: 10.7 CPCB Updates',
    'Training & Awareness: 10.8 Common EPR Portal (CEPR) Introduction covering Portal Structure & Navigation, Workflow & Process Overview, Data Reporting & Verification, Key Features & Enhancements, and Applicability & Compliance Awareness Session',
    'Training & Awareness: 10.8 Q&A / Consultation Support',
    'CTO / CTE Assessment: 12.1 Consent to Establish (CTE) Applicability Assessment',
    'CTO / CTE Assessment: 12.2 Consent to Operate (CTO) Applicability Assessment',
    'CTO / CTE Assessment: 12.5 Consent Validity Review'
  ]),
  superPremium: Object.freeze([
    'Compliance Health Check Report: 1.1 Initial Compliance Assessment & Application Type Evaluation to understand basic compliance gaps',
    'Services: 2.1 Key Account Manager Assigned',
    'Services: 2.2 Compliance Manager Assigned',
    'Services: 2.3 PCB Co-ordinator Assigned',
    'Services: 2.4 On-call Support',
    'Services: 2.5 Annual Return Filing',
    'Services: 2.6 Common SSO Portal Support',
    'Data Analysis: 3.1 Basic Document Assessment (New Application)',
    'Data Analysis: 3.2 Quantity Analysis',
    'Data Analysis: 3.3 GST Analysis (Buyer / Supplier GSTIN)',
    'Data Analysis: 3.4 Plastic Category Classification*',
    'Data Analysis: 3.5 Polymer Type Identification',
    'Data Analysis: 3.6 Container Type Mapping',
    'Data Analysis: 3.7 HSN Code Data Management',
    'Data Management: 4.1 Purchase & Sales Data',
    'Data Management: 4.2 Export / Import Data Verification',
    'Data Management: 4.3 HSN Code Data Management',
    'Data Management: 4.4 Internal Transactions Traceability Assessment',
    'Data Upload & Processing: 5.1 Data Cleaning',
    'Data Upload & Processing: 5.2 Data Formatting',
    'Data Upload & Processing: 5.3 Invoice Mapping',
    'Data Upload & Processing: 5.4 Pre Consumer Data Uploading',
    'Data Upload & Processing: 5.5 Post Consumer Data Uploading',
    'Supplier / Buyer Compliance Management: 6.1 Registered Supplier / Buyer Verification',
    'Supplier / Buyer Compliance Management: 6.2 Unregistered Supplier / Buyer Verification',
    'Supplier / Buyer Compliance Management: 6.3 Recycled Content (PCR) Compliance Guidance & Supplier Confirmation',
    'Supplier / Buyer Compliance Management: 6.4 Supplier / Buyer Training and Awareness',
    'Packaging Material Compliance: 7.1 Basic Category Wise Packaging Assessment*',
    'Packaging Material Compliance: 7.2 Guidance on Primary, Secondary & Tertiary Packaging Identification',
    'Packaging Material Compliance: 7.3 PCR Compliance',
    'Packaging Material Compliance: 7.4 Reuse Compliance (As Applicable)',
    'Packaging Material Compliance: 7.5 Marking & Labelling Compliance',
    'Packaging Material Compliance: 7.6 Packaging Assessment Report',
    'Regulatory Compliance: 8.1 Policy Notification / Circulars Decoding',
    'Regulatory Compliance: 8.2 Personalised Company-level Decoding',
    'Regulatory Compliance: 8.4 Show Cause Notice Reply (Up to 2 Notices)',
    'Regulatory Compliance: 8.5 Guidance & Support in Case of Environmental Compensation (EC) Levied',
    'Regulatory Compliance: 8.6 CPCB Case Representation',
    'Regulatory Compliance: 8.7 Statutory PCR Exemption Support (If Applicable)',
    'Regulatory Compliance: 8.8 Statutory Reuse Exemption Support (If Applicable)',
    'Credit / Obligation Management: 9.1 EPR Target Calculation (Applicable, Actual, Unfulfilled, Minimum Carry Forward)',
    'Credit / Obligation Management: 9.2 Exemption Applicability Check',
    'Credit / Obligation Management: 9.3 Credit Management (Flag Credits, Verified Credits & Credit Offset)',
    'Credit / Obligation Management: 9.4 Carry Forward Eligibility Assessment',
    'Credit / Obligation Management: 9.5 Credit Procurement Support',
    'Credit / Obligation Management: 9.6 Credit Traceability Documentation Compliance',
    'Training & Awareness: 10.1 Formal Explanation of Scope & Deliverables',
    'Training & Awareness: 10.2 Standard Webinars & Knowledge Sessions',
    'Training & Awareness: 10.3 Personalised Webinar & Knowledge Sessions (4 Sessions)',
    'Training & Awareness: 10.4 Multi-department Awareness & Training',
    'Training & Awareness: 10.5 Offline Visit (2 Visits)',
    'Training & Awareness: 10.6 Compliance Awareness Sessions',
    'Training & Awareness: 10.7 CPCB Updates',
    'Training & Awareness: 10.8 Common EPR Portal (CEPR) Introduction covering Portal Structure & Navigation, Workflow & Process Overview, Data Reporting & Verification, Key Features & Enhancements, and Applicability & Compliance Awareness Session',
    'Training & Awareness: 10.8 Q&A / Consultation Support',
    'CTO / CTE Assessment: 12.1 Consent to Establish (CTE) Applicability Assessment',
    'CTO / CTE Assessment: 12.2 Consent to Operate (CTO) Applicability Assessment',
    'CTO / CTE Assessment: 12.3 Water Act Consent Verification',
    'CTO / CTE Assessment: 12.4 Air Act Consent Verification',
    'CTO / CTE Assessment: 12.5 Consent Validity Review',
    'CTO / CTE Assessment: 12.6 Production Capacity Assessment',
    'CTO / CTE Assessment: 12.7 Product & Process Mapping with CTO / CTE',
    'CTO / CTE Assessment: 12.8 Unit-wise Consent Coverage Assessment'
  ])
});
