import React, { useEffect, useMemo, useState } from 'react'
import {
  AlertTriangle, ArrowDown, ArrowUp, CalendarDays, Check, CheckCircle2, ChevronLeft,
  ChevronRight, CircleAlert, Clock3, Download, Ellipsis, FileCheck2, Filter, Play,
  Search, ShieldAlert, ShieldCheck, Sparkles, Target, Upload, X, Zap,
} from 'lucide-react'
import {
  Area, AreaChart, CartesianGrid, Cell, Legend, Line, Pie, PieChart, ReferenceLine,
  ResponsiveContainer, Tooltip, XAxis, YAxis,
} from 'recharts'
import { Activity, ComplianceIssue, Framework, IssueStatus, Severity } from '../features/complianceHealth/types'
import { frameworkScores, initialActivities, initialIssues, riskData, trendData } from '../features/complianceHealth/mockData'
import {
  Badge, Card, CardHeader, ComplianceShell, EmptyState, ErrorState, OwnerCell,
  SeverityBadge, SkeletonDashboard, StatusBadge,
} from '../features/complianceHealth/components'

type TrendKey = 'Overall' | 'Policies' | 'Controls' | 'Evidence' | 'Training'
type SortKey = 'issue' | 'framework' | 'severity' | 'owner' | 'dueDate' | 'status'
const trendColors: Record<TrendKey, string> = { Overall: '#059669', Policies: '#4F46E5', Controls: '#0284C7', Evidence: '#D97706', Training: '#7C3AED' }
const severityRank: Record<Severity, number> = { Critical: 4, High: 3, Medium: 2, Low: 1 }

function ScoreRing() {
  return <div className="relative grid h-40 w-40 shrink-0 place-items-center rounded-full" style={{ background: 'conic-gradient(#059669 0 84%, #E8EEF2 84% 100%)' }} role="img" aria-label="Overall compliance score 84 percent"><div className="grid h-[124px] w-[124px] place-items-center rounded-full bg-white text-center"><div><strong className="block text-4xl font-black tracking-tight text-slate-950">84%</strong><span className="text-[11px] font-extrabold text-slate-500">Health score</span></div></div></div>
}

const kpis = [
  { title: 'Compliant Controls', value: '126 / 142', helper: '89% operating effectively', trend: '+8 this month', up: true, icon: ShieldCheck, tone: 'bg-emerald-50 text-emerald-700' },
  { title: 'Open Issues', value: '16', helper: '5 due within 7 days', trend: '-3 this month', up: true, icon: CircleAlert, tone: 'bg-blue-50 text-blue-700' },
  { title: 'Critical Risks', value: '3', helper: 'Requires immediate action', trend: '+1 this month', up: false, icon: ShieldAlert, tone: 'bg-red-50 text-red-700' },
  { title: 'Evidence Coverage', value: '78%', helper: '111 of 142 controls', trend: '+4% this month', up: true, icon: FileCheck2, tone: 'bg-amber-50 text-amber-700' },
  { title: 'Upcoming Deadlines', value: '7', helper: 'Next: 29 July', trend: '2 high priority', up: false, icon: CalendarDays, tone: 'bg-violet-50 text-violet-700' },
]

function KpiCards() {
  return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{kpis.map(({ title, value, helper, trend, up, icon: Icon, tone }) => <Card key={title} className="p-4 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={19} /></span><span className={`flex items-center gap-1 text-[10px] font-black ${up ? 'text-emerald-700' : 'text-red-600'}`}>{up ? <ArrowUp size={12} /> : <ArrowDown size={12} />}{trend}</span></div><p className="mt-4 text-[11px] font-extrabold text-slate-500">{title}</p><strong className="mt-1 block text-2xl font-black text-slate-950">{value}</strong><p className="mt-1 text-[10px] font-bold text-slate-400">{helper}</p></Card>)}</div>
}

function TrendChart() {
  const [metric, setMetric] = useState<TrendKey>('Overall')
  return <Card className="min-w-0">
    <CardHeader title="Compliance Score Trend" subtitle="Monthly performance across the last 12 months" action={<div className="flex max-w-full gap-1 overflow-x-auto rounded-xl bg-slate-100 p-1">{(Object.keys(trendColors) as TrendKey[]).map((item) => <button key={item} onClick={() => setMetric(item)} className={`rounded-lg px-2.5 py-1.5 text-[10px] font-black transition ${metric === item ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800'}`}>{item}</button>)}</div>} />
    <div className="px-5 pt-4"><div className="flex items-baseline gap-2"><strong className="text-2xl font-black">84%</strong><span className="text-xs font-black text-emerald-700">+2.0%</span><span className="text-xs font-semibold text-slate-400">vs previous period</span></div></div>
    <div className="h-[270px] px-2 pb-4 pt-3">
      <ResponsiveContainer width="100%" height="100%"><AreaChart data={trendData} margin={{ left: -18, right: 14, top: 8 }}><defs><linearGradient id="scoreFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={trendColors[metric]} stopOpacity={.23} /><stop offset="100%" stopColor={trendColors[metric]} stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5EAF0" /><XAxis dataKey="month" tick={{ fontSize: 10, fill: '#64748B', fontWeight: 700 }} tickLine={false} axisLine={false} /><YAxis domain={[50, 100]} tick={{ fontSize: 10, fill: '#64748B' }} tickLine={false} axisLine={false} unit="%" /><Tooltip contentStyle={{ borderRadius: 12, border: '1px solid #E2E8F0', fontSize: 12, boxShadow: '0 10px 30px rgba(15,23,42,.1)' }} /><Legend wrapperStyle={{ fontSize: 11, fontWeight: 700 }} /><ReferenceLine y={90} stroke="#94A3B8" strokeDasharray="5 5" label={{ value: '90% target', fill: '#64748B', fontSize: 10 }} /><Area name={metric} type="monotone" dataKey={metric} stroke={trendColors[metric]} strokeWidth={2.5} fill="url(#scoreFill)" activeDot={{ r: 5 }} /></AreaChart></ResponsiveContainer>
    </div>
  </Card>
}

function FrameworkCard() {
  const [selected, setSelected] = useState<Framework | null>(null)
  return <Card><CardHeader title="Compliance by Framework" subtitle="Control completion and framework readiness" /><div className="divide-y divide-slate-100">{frameworkScores.map((item) => <div key={item.name} className="px-5 py-4 hover:bg-slate-50/70"><div className="flex items-center justify-between gap-3"><div><strong className="text-xs text-slate-800">{item.name}</strong><p className="mt-0.5 text-[10px] font-bold text-slate-400">{item.completed} of {item.total} controls complete</p></div><div className="flex items-center gap-3"><Badge className={item.score >= 85 ? 'bg-emerald-50 text-emerald-700 ring-emerald-200' : item.score >= 75 ? 'bg-amber-50 text-amber-700 ring-amber-200' : 'bg-red-50 text-red-700 ring-red-200'}>{item.score >= 85 ? 'On track' : item.score >= 75 ? 'Needs review' : 'At risk'}</Badge><button className="text-[10px] font-black text-emerald-700 hover:underline" onClick={() => setSelected(item.name)}>View details</button></div></div><div className="mt-3 flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.score >= 85 ? 'bg-emerald-500' : item.score >= 75 ? 'bg-amber-500' : 'bg-red-500'}`} style={{ width: `${item.score}%` }} /></div><strong className="w-9 text-right text-xs">{item.score}%</strong></div></div>)}</div>{selected && <div className="border-t border-emerald-100 bg-emerald-50 px-5 py-3 text-xs font-bold text-emerald-800">{selected} detail view is ready. Select its controls in the issues table below. <button onClick={() => setSelected(null)} className="float-right underline">Dismiss</button></div>}</Card>
}

function RiskDonut() {
  const total = riskData.reduce((sum, item) => sum + item.value, 0)
  return <Card><CardHeader title="Risk Distribution" subtitle="Active risks by severity" /><div className="grid items-center gap-1 p-4 sm:grid-cols-[1.15fr_.85fr]"><div className="relative h-[215px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={riskData} dataKey="value" innerRadius={58} outerRadius={82} paddingAngle={3} stroke="none">{riskData.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip contentStyle={{ borderRadius: 10, fontSize: 11 }} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><strong className="block text-3xl font-black">{total}</strong><span className="text-[10px] font-extrabold text-slate-400">Total risks</span></div></div></div><div className="space-y-3">{riskData.map((item) => <div key={item.name} className="flex items-center gap-2 text-xs"><span className="h-2.5 w-2.5 rounded-full" style={{ background: item.color }} /><span className="font-bold text-slate-600">{item.name}</span><strong className="ml-auto">{item.value}</strong></div>)}</div></div></Card>
}

function IssueDrawer({ issue, onClose, onResolve, onRequest, onToggleStep }: { issue: ComplianceIssue; onClose: () => void; onResolve: () => void; onRequest: () => void; onToggleStep: (id: number) => void }) {
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; document.addEventListener('keydown', handler); return () => document.removeEventListener('keydown', handler) }, [onClose])
  return <><button aria-label="Close issue details" className="fixed inset-0 z-[70] bg-slate-950/35 backdrop-blur-[2px]" onClick={onClose} /><aside role="dialog" aria-modal="true" aria-label={`Issue details: ${issue.issue}`} className="fixed inset-y-0 right-0 z-[80] flex w-full max-w-[520px] flex-col bg-white shadow-2xl">
    <header className="border-b border-slate-200 p-5"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><div className="flex gap-2"><SeverityBadge value={issue.severity} /><StatusBadge value={issue.status} /></div><h2 className="mt-3 text-lg font-black leading-snug text-slate-950">{issue.issue}</h2></div><button onClick={onClose} className="rounded-xl p-2 text-slate-500 hover:bg-slate-100" aria-label="Close drawer"><X size={19} /></button></div></header>
    <div className="flex-1 space-y-6 overflow-y-auto p-5">
      <div><h3 className="text-xs font-black uppercase tracking-wider text-slate-400">Description</h3><p className="mt-2 text-sm font-semibold leading-6 text-slate-600">{issue.description}</p></div>
      <div className="grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-2"><div><span className="text-[10px] font-black uppercase text-slate-400">Framework</span><strong className="mt-1 block text-xs">{issue.framework}</strong></div><div><span className="text-[10px] font-black uppercase text-slate-400">Due date</span><strong className="mt-1 block text-xs">{issue.dueDate}</strong></div><div className="sm:col-span-2"><span className="text-[10px] font-black uppercase text-slate-400">Assigned owner</span><div className="mt-1"><OwnerCell owner={issue.owner} /></div></div></div>
      <div><h3 className="text-xs font-black uppercase tracking-wider text-slate-400">Affected controls</h3><div className="mt-2 flex flex-wrap gap-2">{issue.controls.map((control) => <Badge key={control} className="bg-indigo-50 text-indigo-700 ring-indigo-200">{control}</Badge>)}</div></div>
      <div><h3 className="text-xs font-black uppercase tracking-wider text-slate-400">Remediation steps</h3><div className="mt-2 space-y-2">{issue.remediation.map((step) => <label key={step.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-3 hover:bg-slate-50"><input type="checkbox" checked={step.done} onChange={() => onToggleStep(step.id)} className="h-4 w-4 accent-emerald-600" /><span className={`text-xs font-bold ${step.done ? 'text-slate-400 line-through' : 'text-slate-700'}`}>{step.label}</span></label>)}</div></div>
      <div><div className="flex items-center justify-between"><h3 className="text-xs font-black uppercase tracking-wider text-slate-400">Evidence attachments</h3><button onClick={onRequest} className="text-[10px] font-black text-emerald-700">+ Request evidence</button></div>{issue.evidence.length ? <div className="mt-2 space-y-2">{issue.evidence.map((file) => <div key={file} className="flex items-center gap-2 rounded-xl border border-slate-200 p-3"><FileCheck2 size={17} className="text-emerald-600" /><span className="min-w-0 flex-1 truncate text-xs font-bold">{file}</span><Download size={15} className="text-slate-400" /></div>)}</div> : <p className="mt-2 rounded-xl border border-dashed border-slate-200 p-4 text-center text-xs font-bold text-slate-400">No evidence attached</p>}</div>
      <div><h3 className="text-xs font-black uppercase tracking-wider text-slate-400">Activity timeline</h3><div className="mt-3 space-y-4 border-l border-slate-200 pl-4">{issue.activity.map((item, index) => <div key={index} className="relative"><span className="absolute -left-[21px] top-1 h-2.5 w-2.5 rounded-full bg-emerald-500 ring-4 ring-white" /><p className="text-xs font-bold text-slate-700">{item.label}</p><span className="text-[10px] font-semibold text-slate-400">{item.time}</span></div>)}</div></div>
    </div>
    <footer className="flex gap-3 border-t border-slate-200 p-4"><button onClick={onRequest} className="flex-1 rounded-xl border border-slate-200 px-4 py-3 text-xs font-black hover:bg-slate-50"><Upload className="mr-2 inline" size={15} />Request Evidence</button><button disabled={issue.status === 'Resolved'} onClick={onResolve} className="flex-1 rounded-xl bg-emerald-600 px-4 py-3 text-xs font-black text-white hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-50"><CheckCircle2 className="mr-2 inline" size={15} />Mark as Resolved</button></footer>
  </aside></>
}

function PriorityIssues({ issues, setIssues, notify }: { issues: ComplianceIssue[]; setIssues: React.Dispatch<React.SetStateAction<ComplianceIssue[]>>; notify: (message: string) => void }) {
  const [query, setQuery] = useState('')
  const [filters, setFilters] = useState({ severity: '', framework: '', owner: '', status: '' })
  const [sort, setSort] = useState<{ key: SortKey; direction: 'asc' | 'desc' }>({ key: 'severity', direction: 'desc' })
  const [selected, setSelected] = useState<ComplianceIssue | null>(null)
  const [filterOpen, setFilterOpen] = useState(false)
  const [page, setPage] = useState(1)
  const pageSize = 4
  const setFilter = (key: keyof typeof filters, value: string) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1) }
  const filtered = useMemo(() => issues.filter((issue) => issue.issue.toLowerCase().includes(query.toLowerCase()) && (!filters.severity || issue.severity === filters.severity) && (!filters.framework || issue.framework === filters.framework) && (!filters.owner || issue.owner.name === filters.owner) && (!filters.status || issue.status === filters.status)).sort((a, b) => {
    let av: string | number = sort.key === 'owner' ? a.owner.name : sort.key === 'severity' ? severityRank[a.severity] : String(a[sort.key])
    let bv: string | number = sort.key === 'owner' ? b.owner.name : sort.key === 'severity' ? severityRank[b.severity] : String(b[sort.key])
    return (av < bv ? -1 : av > bv ? 1 : 0) * (sort.direction === 'asc' ? 1 : -1)
  }), [issues, query, filters, sort])
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize))
  const visible = filtered.slice((page - 1) * pageSize, page * pageSize)
  const toggleSort = (key: SortKey) => setSort((current) => ({ key, direction: current.key === key && current.direction === 'asc' ? 'desc' : 'asc' }))
  const reset = () => { setQuery(''); setFilters({ severity: '', framework: '', owner: '', status: '' }); setPage(1) }
  const updateSelected = (fn: (issue: ComplianceIssue) => ComplianceIssue) => { if (!selected) return; const next = fn(selected); setSelected(next); setIssues((current) => current.map((item) => item.id === next.id ? next : item)) }
  const selectClass = 'h-9 rounded-lg border border-slate-200 bg-white px-2 text-[11px] font-bold text-slate-600 outline-none focus:border-emerald-500'
  return <><Card><CardHeader title="Priority Compliance Issues" subtitle={`${filtered.length} issues match the current view`} action={<button onClick={reset} className="text-[11px] font-black text-emerald-700 hover:underline">Clear filters</button>} />
    <div className="border-b border-slate-100 p-4"><div className="flex flex-wrap gap-2"><label className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={15} /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1) }} className="h-9 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-xs outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10" placeholder="Search issues…" aria-label="Search compliance issues" /></label><button onClick={() => setFilterOpen(true)} className="flex h-9 items-center gap-2 rounded-lg border border-slate-200 px-3 text-[11px] font-black md:hidden"><Filter size={14} />Filters</button><div className="hidden flex-wrap gap-2 md:flex"><select value={filters.severity} onChange={(e) => setFilter('severity', e.target.value)} className={selectClass} aria-label="Filter by severity"><option value="">All severities</option>{['Critical','High','Medium','Low'].map((item) => <option key={item}>{item}</option>)}</select><select value={filters.framework} onChange={(e) => setFilter('framework', e.target.value)} className={selectClass} aria-label="Filter by framework"><option value="">All frameworks</option>{frameworkScores.map((item) => <option key={item.name}>{item.name}</option>)}</select><select value={filters.owner} onChange={(e) => setFilter('owner', e.target.value)} className={selectClass} aria-label="Filter by owner"><option value="">All owners</option>{Array.from(new Set(issues.map((item) => item.owner.name))).map((item) => <option key={item}>{item}</option>)}</select><select value={filters.status} onChange={(e) => setFilter('status', e.target.value)} className={selectClass} aria-label="Filter by status"><option value="">All statuses</option>{['Open','In progress','Awaiting evidence','Resolved'].map((item) => <option key={item}>{item}</option>)}</select></div></div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[1040px] text-left"><thead><tr className="border-b border-slate-200 bg-slate-50/80">{([['issue','Issue'],['framework','Framework'],['severity','Severity'],['owner','Owner'],['dueDate','Due date'],['status','Status']] as [SortKey,string][]).map(([key,label]) => <th key={key} className="px-4 py-3 text-[10px] font-black uppercase tracking-wider text-slate-500"><button className="flex items-center gap-1 hover:text-slate-900" onClick={() => toggleSort(key)}>{label}{sort.key === key && (sort.direction === 'asc' ? <ArrowUp size={11} /> : <ArrowDown size={11} />)}</button></th>)}<th className="px-4 py-3 text-[10px] font-black uppercase tracking-wider text-slate-500">Actions</th></tr></thead><tbody>{visible.map((issue) => <tr key={issue.id} tabIndex={0} role="button" onClick={() => setSelected(issue)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') setSelected(issue) }} className="cursor-pointer border-b border-slate-100 outline-none transition hover:bg-emerald-50/40 focus:bg-emerald-50"><td className="max-w-[310px] px-4 py-3"><strong className="block truncate text-xs text-slate-800">{issue.issue}</strong><span className="text-[10px] font-bold text-slate-400">ISS-{String(issue.id).padStart(3,'0')}</span></td><td className="px-4 py-3 text-xs font-bold text-slate-600">{issue.framework}</td><td className="px-4 py-3"><SeverityBadge value={issue.severity} /></td><td className="px-4 py-3"><OwnerCell owner={issue.owner} /></td><td className="px-4 py-3 text-xs font-bold text-slate-600">{issue.dueDate}</td><td className="px-4 py-3"><StatusBadge value={issue.status} /></td><td className="px-4 py-3"><button onClick={(event) => { event.stopPropagation(); setSelected(issue) }} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label={`Actions for ${issue.issue}`}><Ellipsis size={17} /></button></td></tr>)}</tbody></table>{!visible.length && <EmptyState title="No issues found" detail="Try changing your search or filters." onReset={reset} />}</div>
    {!!visible.length && <div className="flex items-center justify-between border-t border-slate-100 px-4 py-3"><span className="text-[10px] font-bold text-slate-500">Showing {(page - 1) * pageSize + 1}–{Math.min(page * pageSize, filtered.length)} of {filtered.length}</span><div className="flex gap-1"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)} className="rounded-lg border border-slate-200 p-2 disabled:opacity-40" aria-label="Previous page"><ChevronLeft size={14} /></button><span className="grid min-w-8 place-items-center rounded-lg bg-slate-100 text-[10px] font-black">{page}/{pages}</span><button disabled={page === pages} onClick={() => setPage((value) => value + 1)} className="rounded-lg border border-slate-200 p-2 disabled:opacity-40" aria-label="Next page"><ChevronRight size={14} /></button></div></div>}</Card>
    {filterOpen && <><button className="fixed inset-0 z-[70] bg-slate-950/35 md:hidden" onClick={() => setFilterOpen(false)} aria-label="Close filters" /><aside className="fixed inset-x-0 bottom-0 z-[80] rounded-t-2xl bg-white p-5 shadow-2xl md:hidden"><div className="flex items-center justify-between"><h3 className="font-black">Filter issues</h3><button onClick={() => setFilterOpen(false)}><X size={19} /></button></div><div className="mt-4 grid gap-3"><select value={filters.severity} onChange={(e) => setFilter('severity', e.target.value)} className={selectClass}><option value="">All severities</option>{['Critical','High','Medium','Low'].map((item) => <option key={item}>{item}</option>)}</select><select value={filters.framework} onChange={(e) => setFilter('framework', e.target.value)} className={selectClass}><option value="">All frameworks</option>{frameworkScores.map((item) => <option key={item.name}>{item.name}</option>)}</select><select value={filters.owner} onChange={(e) => setFilter('owner', e.target.value)} className={selectClass}><option value="">All owners</option>{Array.from(new Set(issues.map((item) => item.owner.name))).map((item) => <option key={item}>{item}</option>)}</select><select value={filters.status} onChange={(e) => setFilter('status', e.target.value)} className={selectClass}><option value="">All statuses</option>{['Open','In progress','Awaiting evidence','Resolved'].map((item) => <option key={item}>{item}</option>)}</select><button onClick={() => setFilterOpen(false)} className="rounded-xl bg-emerald-600 py-3 text-xs font-black text-white">Show {filtered.length} issues</button></div></aside></>}
    {selected && <IssueDrawer issue={selected} onClose={() => setSelected(null)} onResolve={() => { updateSelected((item) => ({ ...item, status: 'Resolved' })); notify('Issue marked as resolved') }} onRequest={() => notify('Evidence request sent to the issue owner')} onToggleStep={(id) => updateSelected((item) => ({ ...item, remediation: item.remediation.map((step) => step.id === id ? { ...step, done: !step.done } : step) }))} />}</>
}

function ActivitiesCard({ activities, setActivities }: { activities: Activity[]; setActivities: React.Dispatch<React.SetStateAction<Activity[]>> }) {
  return <Card><CardHeader title="Upcoming Activities" subtitle="Next compliance obligations" /><div className="divide-y divide-slate-100">{activities.map((item) => <label key={item.id} className="flex cursor-pointer items-start gap-3 px-5 py-3.5 hover:bg-slate-50"><input type="checkbox" checked={item.complete} onChange={() => setActivities((current) => current.map((activity) => activity.id === item.id ? { ...activity, complete: !activity.complete } : activity))} className="mt-1 h-4 w-4 accent-emerald-600" /><div className="min-w-0 flex-1"><p className={`truncate text-xs font-black ${item.complete ? 'text-slate-400 line-through' : 'text-slate-800'}`}>{item.title}</p><p className="mt-1 text-[10px] font-bold text-slate-400">{item.date} · {item.owner}</p></div><SeverityBadge value={item.priority} /></label>)}</div></Card>
}

function Recommendations({ notify }: { notify: (message: string) => void }) {
  const items = [
    { title: 'Enforce MFA for all administrator accounts', gain: '+4.2%', effort: 'Low', action: 'Apply' },
    { title: 'Complete overdue vendor assessments', gain: '+2.8%', effort: 'Medium', action: 'Create Task' },
    { title: 'Upload missing training evidence', gain: '+1.6%', effort: 'Low', action: 'Create Task' },
  ]
  return <Card><CardHeader title="AI Recommendations" subtitle="Prioritized actions to improve your health score" action={<Sparkles size={18} className="text-violet-600" />} /><div className="grid gap-3 p-4 md:grid-cols-3">{items.map((item) => <div key={item.title} className="rounded-xl border border-slate-200 p-4 transition hover:border-violet-200 hover:shadow-sm"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-700"><Zap size={17} /></span><div><h3 className="text-xs font-black leading-5 text-slate-800">{item.title}</h3><div className="mt-2 flex gap-2"><Badge className="bg-emerald-50 text-emerald-700 ring-emerald-200">{item.gain} score</Badge><Badge className="bg-slate-50 text-slate-600 ring-slate-200">{item.effort} effort</Badge></div></div></div><button onClick={() => notify(`${item.action === 'Apply' ? 'Recommendation applied' : 'Task created'}: ${item.title}`)} className="mt-4 w-full rounded-lg border border-violet-200 px-3 py-2 text-[11px] font-black text-violet-700 hover:bg-violet-50 focus:ring-4 focus:ring-violet-100">{item.action}</button></div>)}</div></Card>
}

export default function ComplianceHealthDashboard() {
  const [collapsed, setCollapsed] = useState(false)
  const [mobileOpen, setMobileOpen] = useState(false)
  const [range, setRange] = useState('Last 30 days')
  const [customDates, setCustomDates] = useState({ from: '2026-07-01', to: '2026-07-24' })
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)
  const [scanning, setScanning] = useState(false)
  const [toast, setToast] = useState('')
  const [issues, setIssues] = useState(initialIssues)
  const [activities, setActivities] = useState(initialActivities)
  useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 650); return () => window.clearTimeout(timer) }, [])
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''), 3000); return () => window.clearTimeout(timer) }, [toast])
  const runScan = () => { setScanning(true); window.setTimeout(() => { setScanning(false); setToast('Compliance scan completed successfully') }, 950) }
  const exportReport = () => {
    const blob = new Blob([JSON.stringify({ generatedAt: new Date().toISOString(), score: 84, issues }, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'compliance-health-report.json'; link.click(); URL.revokeObjectURL(url); setToast('Compliance report exported successfully')
  }
  return <ComplianceShell collapsed={collapsed} onCollapse={() => setCollapsed((value) => !value)} mobileOpen={mobileOpen} onMobileClose={() => setMobileOpen((value) => !value)}>
    {loading ? <SkeletonDashboard /> : error ? <ErrorState onRetry={() => { setError(false); setLoading(true); window.setTimeout(() => setLoading(false), 650) }} /> : <div className="mx-auto max-w-[1600px] space-y-5 p-4 md:p-6 xl:p-7">
      <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[11px] font-extrabold text-slate-500">Compliance <span className="px-1 text-slate-300">/</span> Health Report</p><h1 className="mt-2 text-2xl font-black tracking-tight text-slate-950 md:text-[28px]">Compliance Health Report</h1><p className="mt-1.5 max-w-2xl text-sm font-semibold text-slate-500">Monitor your organization’s compliance posture, risks, controls, and upcoming obligations.</p><p className="mt-2 flex items-center gap-2 text-[10px] font-bold text-slate-400"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500" />Last updated 5 minutes ago</p></div><div className="flex flex-wrap gap-2"><select value={range} onChange={(event) => setRange(event.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs font-black text-slate-700 outline-none focus:border-emerald-500" aria-label="Report date range">{['Last 30 days','Last quarter','This year','Custom'].map((item) => <option key={item}>{item}</option>)}</select>{range === 'Custom' && <><input type="date" value={customDates.from} onChange={(event) => setCustomDates((value) => ({ ...value, from: event.target.value }))} className="h-10 rounded-xl border border-slate-200 bg-white px-2 text-xs font-bold" aria-label="Custom range start" /><input type="date" value={customDates.to} min={customDates.from} onChange={(event) => setCustomDates((value) => ({ ...value, to: event.target.value }))} className="h-10 rounded-xl border border-slate-200 bg-white px-2 text-xs font-bold" aria-label="Custom range end" /></>}<button onClick={exportReport} className="h-10 rounded-xl border border-slate-200 bg-white px-4 text-xs font-black text-slate-700 shadow-sm hover:bg-slate-50 focus:ring-4 focus:ring-slate-100"><Download className="mr-2 inline" size={15} />Export Report</button><button disabled={scanning} onClick={runScan} className="h-10 rounded-xl bg-emerald-600 px-4 text-xs font-black text-white shadow-sm shadow-emerald-200 hover:bg-emerald-700 focus:ring-4 focus:ring-emerald-200 disabled:opacity-60"><Play className={`mr-2 inline ${scanning ? 'animate-spin' : ''}`} size={15} />{scanning ? 'Scanning…' : 'Run Compliance Scan'}</button></div></div>
      <Card className="p-5 md:p-6"><div className="grid items-center gap-6 lg:grid-cols-[auto_1fr_1fr]"><ScoreRing /><div><div className="flex items-center gap-2"><h2 className="text-lg font-black">Overall Compliance Health</h2><Badge className="bg-emerald-50 text-emerald-700 ring-emerald-200">Good</Badge></div><p className="mt-2 text-xs font-black text-emerald-700">+6% from last month</p><p className="mt-3 max-w-xl text-sm font-semibold leading-6 text-slate-500">Most controls are operating effectively. Three high-priority issues require attention.</p></div><div className="grid grid-cols-2 gap-4">{[['Policies',92],['Controls',87],['Evidence',78],['Training',81]].map(([label,value]) => <div key={label as string}><div className="flex justify-between text-[11px] font-black"><span className="text-slate-500">{label}</span><span>{value}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${value}%` }} /></div></div>)}</div></div></Card>
      <KpiCards />
      <div className="grid min-w-0 gap-5 xl:grid-cols-[1.65fr_1fr]"><TrendChart /><RiskDonut /></div>
      <div className="grid min-w-0 gap-5 xl:grid-cols-[1.35fr_1fr]"><FrameworkCard /><ActivitiesCard activities={activities} setActivities={setActivities} /></div>
      <PriorityIssues issues={issues} setIssues={setIssues} notify={setToast} />
      <Recommendations notify={setToast} />
    </div>}
    <button onClick={() => setError(true)} className="sr-only">Simulate report error</button>
    {toast && <div role="status" aria-live="polite" className="fixed bottom-5 right-5 z-[100] flex max-w-sm items-center gap-3 rounded-xl bg-slate-950 px-4 py-3 text-xs font-black text-white shadow-2xl"><Check size={17} className="text-emerald-400" />{toast}<button onClick={() => setToast('')} aria-label="Dismiss notification"><X size={15} /></button></div>}
  </ComplianceShell>
}
