const BUILT_IN_SERVICE_CATEGORIES = Object.freeze([
  'CASE REPRESENTATION',
  'CAT-1-EOL CREDIT',
  'CAT-1-RECYCLING CREDIT',
  'CAT-2-EOL CREDIT',
  'CAT-2-RECYCLING CREDIT',
  'CAT-3-EOL CREDIT',
  'CAT-3-RECYCLING CREDIT',
  'CATEGORY 1',
  'CATEGORY 2',
  'CATEGORY 3',
  'CGWA NOC FRESH APPLICATION',
  'CONSULTANCY FEE',
  'CPCB NOTICE REPLY FEES',
  'CTE & CTO NEW REGISTRATION',
  'CTE - CONSENT TO ESTABLISH',
  'CTO - CONSENT TO OPERATE',
  'CTO - RENEWAL',
  'E-WASTE CREDIT',
  'ENVIRONMENT STATEMENT FORM V SUBMISSION',
  'EPR CREDIT RE',
  'EPR CREDIT REVENUE SHARING',
  'EPR ETP PORTAL HANDLING CHARGES',
  'EPR LOGIN SURRENDER',
  'GOVT. REPRESENTATION CHARGES',
  'KAVACH AUDIT',
  'MATERIAL WASTE DISPOSAL CONSULTANCY',
  'PLANT AUDIT',
  'PORTAL HEALTH REPORT CONSULTANCY',
  'SAP INTEGRATION SUPPORT',
  'UREP ASSESSMENT AND CONSULTING'
]);

function normalizeServiceCategoryName(value) {
  return String(value || '').trim().replace(/\s+/g, ' ').toUpperCase();
}

module.exports = {
  BUILT_IN_SERVICE_CATEGORIES,
  normalizeServiceCategoryName
};
