import React, { useEffect, useState } from 'react';
import { Download, ExternalLink, FileText, Loader2, Mail, Paperclip, X } from 'lucide-react';
import api from '../../services/api';
import { API_ENDPOINTS } from '../../services/apiEndpoints';

const fileUrl = (file) => file?.secureUrl || file?.url || '';
export function isEmailProof(file) { return /\.(eml|msg)$/i.test(String(file?.name || file?.originalName || '')) || ['message/rfc822', 'application/vnd.ms-outlook'].includes(String(file?.type || file?.mimeType || '').toLowerCase()); }
export function isOutlookMsg(file) { return /\.msg$/i.test(String(file?.name || file?.originalName || '')) || String(file?.type || file?.mimeType || '').toLowerCase() === 'application/vnd.ms-outlook'; }

function attachmentMime(name) { const extension = String(name || '').split('.').pop()?.toLowerCase(); return ({ pdf: 'application/pdf', png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', txt: 'text/plain', csv: 'text/csv', xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' })[extension] || 'application/octet-stream'; }
function cleanBody(value) { const raw = String(value || ''); if (!raw.includes('<')) return raw.trim(); const parsed = new DOMParser().parseFromString(raw, 'text/html'); return String(parsed.body?.textContent || '').replace(/\n{3,}/g, '\n\n').trim(); }
function addressText(value) { if (Array.isArray(value)) return value.map((item) => item.email ? `${item.name ? `${item.name} ` : ''}<${item.email}>` : item.name).filter(Boolean).join(', '); return [value?.name, value?.email].filter(Boolean).join(' · '); }
function saveBlob(blob, name, open = false) { const url = URL.createObjectURL(blob); if (open) window.open(url, '_blank', 'noopener,noreferrer'); else { const anchor = document.createElement('a'); anchor.href = url; anchor.download = name || 'download'; anchor.click(); } setTimeout(() => URL.revokeObjectURL(url), 30000); }

export default function OutlookMsgViewer({ file, onClose }) {
  const [state, setState] = useState({ loading: true, error: '', mail: null, attachments: [] });
  const [tab, setTab] = useState('Email');
  const [downloading, setDownloading] = useState('');
  const sourceUrl = fileUrl(file);

  useEffect(() => {
    let active = true; const objectUrls = [];
    (async () => {
      try {
        if (file?.proofId) { const { data } = await api.get(API_ENDPOINTS.purchaseProofs.detail(file.proofId)); const proof = data.proof || file; if (active) setState({ loading: false, error: '', mail: proof.emailData || {}, attachments: proof.emailData?.attachments || [] }); return; }
        if (!isOutlookMsg(file)) throw new Error('This legacy EML proof has no saved decoded metadata. Please upload it again.');
        const response = await fetch(sourceUrl); if (!response.ok) throw new Error(`Mail download failed (${response.status}).`);
        const { default: MsgReader } = await import('@kenjiuno/msgreader'); const reader = new MsgReader(await response.arrayBuffer()); const raw = reader.getFileData(); if (raw?.error) throw new Error(raw.error);
        const attachments = (raw?.attachments || []).map((item, index) => { const decoded = reader.getAttachment(item); const fileName = decoded?.fileName || item.fileName || item.fileNameShort || `attachment-${index + 1}`; const url = URL.createObjectURL(new Blob([decoded?.content || new Uint8Array()], { type: attachmentMime(fileName) })); objectUrls.push(url); return { attachmentId: String(index), fileName, url, size: decoded?.content?.byteLength || item.contentLength || 0, contentType: attachmentMime(fileName), isInline: false }; });
        const mail = { format: 'msg', subject: raw.subject, from: { name: raw.senderName, email: raw.senderEmail }, to: (raw.recipients || []).map((item) => ({ name: item.name, email: item.email })), cc: [], sentAt: raw.clientSubmitTime, receivedAt: raw.messageDeliveryTime || raw.creationTime, textBody: raw.body, sanitizedHtmlBody: raw.bodyHTML || raw.htmlBody, headers: [], attachments, decodeStatus: 'Decoded', decodeWarnings: [] };
        if (active) setState({ loading: false, error: '', mail, attachments });
      } catch (error) { if (active) setState({ loading: false, error: error.message || 'Unable to decode this email.', mail: file?.emailData || null, attachments: file?.emailData?.attachments || [] }); }
    })();
    return () => { active = false; objectUrls.forEach((url) => URL.revokeObjectURL(url)); };
  }, [file, sourceUrl]);

  const mail = state.mail || file?.emailData || {}; const body = cleanBody(mail.textBody || mail.sanitizedHtmlBody || mail.body || ''); const badge = String(mail.format || file?.fileType || (isOutlookMsg(file) ? 'msg' : 'eml')).toUpperCase(); const tabs = ['Email', 'Attachments', 'Headers', 'File Information'];
  const downloadOriginal = async (open = false) => { setDownloading('original'); try { if (file.proofId) { const response = await api.get(API_ENDPOINTS.purchaseProofs.download(file.proofId), { responseType: 'blob' }); saveBlob(response.data, file.name, open); } else if (open) window.open(sourceUrl, '_blank', 'noopener,noreferrer'); else { const response = await fetch(sourceUrl); saveBlob(await response.blob(), file.name); } } finally { setDownloading(''); } };
  const downloadAttachment = async (attachment) => { setDownloading(attachment.attachmentId); try { if (file.proofId && attachment.attachmentId) { const response = await api.get(API_ENDPOINTS.purchaseProofs.attachment(file.proofId, attachment.attachmentId), { responseType: 'blob' }); saveBlob(response.data, attachment.fileName); } else if (attachment.url) saveBlob(await (await fetch(attachment.url)).blob(), attachment.fileName); } finally { setDownloading(''); } };

  return <div className="fixed inset-0 z-[180] bg-slate-950/70 p-2 sm:p-5" role="dialog" aria-modal="true" aria-label="Email proof preview"><div className="mx-auto flex h-full max-w-7xl flex-col overflow-hidden rounded-3xl bg-white shadow-2xl">
    <header className="flex flex-wrap items-start justify-between gap-3 border-b border-emerald-100 bg-[linear-gradient(90deg,#fff,#f0fdf9)] p-5"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em] text-emerald-700">Preview</span><span className="rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-black text-slate-600">Email File ({badge})</span><StatusBadge value={mail.decodeStatus} /></div><h4 className="mt-3 text-lg font-black text-slate-950">{file?.name || 'Email proof'}</h4><p className="mt-1 text-sm font-bold text-slate-500">Server-decoded metadata with safe text rendering and protected downloads.</p></div><div className="flex items-center gap-2"><button type="button" onClick={() => downloadOriginal(true)} disabled={downloading === 'original'} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-black text-slate-700"><ExternalLink className="h-4 w-4" />Open</button><button type="button" onClick={() => downloadOriginal(false)} disabled={downloading === 'original'} className="inline-flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-sm font-black text-emerald-700">{downloading === 'original' ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}Download</button><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 bg-white p-2.5 text-slate-600"><X className="h-5 w-5" /></button></div></header>
    <nav className="flex gap-1 overflow-x-auto border-b border-slate-200 bg-white p-2">{tabs.map((item) => <button type="button" key={item} onClick={() => setTab(item)} className={`whitespace-nowrap rounded-lg px-4 py-2 text-xs font-black ${tab === item ? 'bg-[#087A70] text-white' : 'text-slate-600 hover:bg-slate-100'}`}>{item}</button>)}</nav>
    <main className="flex-1 overflow-y-auto bg-slate-50/70 p-4 sm:p-6">{state.loading && <Loading />}{state.error && !state.mail && <ErrorState message={state.error} />}{!state.loading && (state.mail || file?.emailData) && <>{state.error && <div className="mb-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-bold text-amber-800">{state.error}</div>}
      {tab === 'Email' && <div className="space-y-5"><section className="overflow-hidden rounded-3xl border border-emerald-100 bg-white shadow-sm"><div className="border-b border-emerald-100 bg-emerald-50/70 p-5"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-700">Mail Summary</p><h5 className="mt-2 text-xl font-black text-slate-950">{mail.subject || '(No subject)'}</h5>{mail.decodeWarnings?.map((warning) => <p key={warning} className="mt-1 text-xs font-bold text-amber-700">Warning: {warning}</p>)}</div><div className="grid gap-4 p-5 md:grid-cols-2 lg:grid-cols-3"><Info label="From" value={addressText(mail.from) || '-'} /><Info label="To" value={addressText(mail.to) || '-'} /><Info label="CC" value={addressText(mail.cc) || '-'} /><Info label="Sent" value={mail.sentAt ? new Date(mail.sentAt).toLocaleString('en-IN') : '-'} /><Info label="Received" value={mail.receivedAt ? new Date(mail.receivedAt).toLocaleString('en-IN') : '-'} /><Info label="Message ID" value={mail.messageId || '-'} /></div></section><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-500">Message Body</p><p className="mt-1 text-sm font-bold text-slate-500">Clean text view; scripts and remote images are never rendered.</p></div><pre className="min-h-48 whitespace-pre-wrap break-words p-6 font-sans text-sm font-medium leading-7 text-slate-700">{body || 'No readable message body was found.'}</pre></section></div>}
      {tab === 'Attachments' && <AttachmentTable attachments={state.attachments} downloading={downloading} onDownload={downloadAttachment} />}
      {tab === 'Headers' && <section className="overflow-hidden rounded-2xl border bg-white"><table className="w-full text-left text-xs"><thead className="bg-slate-100"><tr><th className="px-4 py-3">Header</th><th className="px-4 py-3">Value</th></tr></thead><tbody>{(mail.headers || []).map((header, index) => <tr key={`${header.name}-${index}`} className="border-t"><td className="px-4 py-3 font-black">{header.name}</td><td className="break-all px-4 py-3 font-bold text-slate-600">{header.value}</td></tr>)}{!mail.headers?.length && <tr><td colSpan="2" className="p-8 text-center font-bold text-slate-400">No internet headers available.</td></tr>}</tbody></table></section>}
      {tab === 'File Information' && <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Info label="File name" value={file.name || '-'} /><Info label="Format" value={badge} /><Info label="MIME type" value={file.mimeType || file.type || '-'} /><Info label="File size" value={file.size ? `${Math.ceil(file.size / 1024)} KB` : '-'} /><Info label="Decode status" value={mail.decodeStatus || '-'} /><Info label="Uploaded at" value={file.uploadedAt ? new Date(file.uploadedAt).toLocaleString('en-IN') : '-'} /></div>}
    </>}</main>
  </div></div>;
}

function StatusBadge({ value }) { const failed = value === 'Failed'; return <span className={`rounded-full border px-3 py-1 text-[10px] font-black uppercase ${failed ? 'border-rose-200 bg-rose-50 text-rose-700' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{value || 'Decoded'}</span>; }
function Loading() { return <div className="grid min-h-80 place-items-center"><div className="text-center"><Loader2 className="mx-auto h-8 w-8 animate-spin text-emerald-600" /><p className="mt-3 text-sm font-black text-slate-600">Loading decoded email…</p></div></div>; }
function ErrorState({ message }) { return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-center"><Mail className="mx-auto h-8 w-8 text-rose-500" /><h5 className="mt-3 font-black text-rose-800">Mail preview unavailable</h5><p className="mt-2 text-sm font-bold text-rose-700">{message}</p></div>; }
function Info({ label, value }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4"><span className="text-[10px] font-black uppercase tracking-widest text-slate-500">{label}</span><strong className="mt-2 block break-words text-sm text-slate-800">{value}</strong></div>; }
function AttachmentTable({ attachments, downloading, onDownload }) { return <section className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center gap-2 border-b p-4"><Paperclip className="h-4 w-4" /><h6 className="text-sm font-black">Attachments ({attachments.length})</h6></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-slate-100"><tr><th className="px-4 py-3">Attachment</th><th>Type</th><th>Size</th><th>Inline</th><th>Action</th></tr></thead><tbody>{attachments.map((attachment) => <tr key={attachment.attachmentId || attachment.fileName} className="border-t"><td className="px-4 py-3 font-black"><span className="flex items-center gap-2"><FileText className="h-4 w-4 text-emerald-600" />{attachment.fileName}</span></td><td>{attachment.contentType || '-'}</td><td>{attachment.size ? `${Math.ceil(attachment.size / 1024)} KB` : '-'}</td><td>{attachment.isInline ? 'Yes' : 'No'}</td><td><button type="button" onClick={() => onDownload(attachment)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 font-black text-emerald-700">{downloading === attachment.attachmentId ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}Download</button></td></tr>)}{!attachments.length && <tr><td colSpan="5" className="p-8 text-center font-bold text-slate-400">No attachment files were found.</td></tr>}</tbody></table></div></section>; }

