import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, Check, CheckCircle2, Download, FileSpreadsheet, History, Loader2, RefreshCw, ShieldCheck, Trash2, Upload, X } from 'lucide-react';
import api from '../../services/api';
import { API_ENDPOINTS } from '../../services/apiEndpoints';
import { uploadMedia, uploadMediaBatch } from '../../services/mediaUpload';
import { downloadCsv, downloadDataTemplate, formatMetric, readPurchaseWorkbook } from './purchaseData.utils';
import SalesUploadChecklist from './SalesUploadChecklist';
import OutlookMsgViewer from './OutlookMsgViewer';

const errorText = (error) => error?.response?.data?.error || error?.response?.data?.message || error?.message || 'Something went wrong.';
const tone = (value) => {
  const status = String(value || '').toLowerCase();
  if (status.includes('approved') || status.includes('matched') || status.includes('imported')) return 'border-emerald-200 bg-emerald-50 text-emerald-700';
  if (status.includes('reject') || status.includes('missing') || status.includes('excess')) return 'border-rose-200 bg-rose-50 text-rose-700';
  if (status.includes('pending') || status.includes('warning') || status.includes('partial')) return 'border-amber-200 bg-amber-50 text-amber-700';
  return 'border-slate-200 bg-slate-50 text-slate-600';
};
function Badge({ children, value = children }) { return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-black uppercase tracking-wide ${tone(value)}`}>{children}</span>; }
function Metric({ label, value, accent = '' }) { return <div className={`rounded-xl border p-3 ${accent || 'border-slate-200 bg-slate-50'}`}><p className="text-[10px] font-black uppercase tracking-widest text-slate-500">{label}</p><strong className="mt-1 block text-lg font-black text-slate-950">{value}</strong></div>; }

function Workflow({ sales }) {
  const steps = [['Sales Base Excel', Boolean(sales.baseUpload)], ['Sales Portal Excel', Boolean(sales.portalUpload)], ['Manager Review', ['Approved', 'Rejected'].includes(sales.managerVerificationStatus), sales.managerVerificationStatus], ['Compliance Review', ['Approved', 'Rejected'].includes(sales.complianceVerificationStatus), sales.complianceVerificationStatus]];
  return <div className="grid gap-2 md:grid-cols-4">{steps.map(([label, done, status], index) => <div key={label} className={`rounded-xl border p-3 ${done ? 'border-emerald-200 bg-emerald-50' : 'border-slate-200 bg-white'}`}><div className="flex items-center gap-2"><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-black ${done ? 'bg-emerald-600 text-white' : 'bg-slate-100 text-slate-500'}`}>{done ? <Check className="h-4 w-4" /> : index + 1}</span><div><p className="text-xs font-black text-slate-900">{label}</p><p className="text-[10px] font-bold text-slate-500">{status || (done ? 'Completed' : 'Required')}</p></div></div></div>)}</div>;
}

function UploadCard({ source, upload, disabled, busy, financialYear, onSelect, onRemove }) {
  const title = source === 'base' ? 'Sales Base Data' : 'Sales Portal Upload';
  return <article className={`overflow-hidden rounded-2xl border ${upload ? 'border-emerald-200 bg-emerald-50/40' : 'border-slate-200 bg-white'}`}><div className="flex items-start justify-between gap-3 border-b border-inherit p-4"><div><h6 className="text-sm font-black text-slate-950">{title}</h6><p className="mt-1 text-xs font-bold text-slate-500">{source === 'base' ? 'Quantity (TPA)' : 'Total Plastic Qty (Tons)'} required</p></div><button type="button" onClick={() => downloadDataTemplate(source, financialYear, 'sales')} className="inline-flex items-center gap-1 rounded-lg border bg-white px-3 py-2 text-xs font-black"><Download className="h-3.5 w-3.5" />Template</button></div>
    {upload ? <div className="p-4"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><FileSpreadsheet className="h-5 w-5" /></span><div className="min-w-0 flex-1"><a href={upload.secureUrl || upload.url} target="_blank" rel="noreferrer" className="block truncate text-sm font-black text-emerald-800 hover:underline">{upload.name}</a><p className="mt-1 text-xs font-bold text-slate-500">{upload.totalRows} rows · {formatMetric(upload.totalQuantity)} tons · {upload.warningRowCount || 0} warnings</p></div>{!disabled && <button type="button" onClick={() => onRemove(source)} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50"><Trash2 className="h-4 w-4" /></button>}</div>{!disabled && <label className="mt-4 inline-flex cursor-pointer rounded-lg border border-emerald-200 bg-white px-3 py-2 text-xs font-black">Replace file<input className="hidden" type="file" accept=".xlsx,.xls" disabled={busy} onChange={(event) => onSelect(source, event.target.files?.[0], event.target)} /></label>}</div> : <label className={`m-4 grid min-h-32 place-items-center rounded-xl border-2 border-dashed text-center ${disabled ? 'cursor-not-allowed border-slate-200 bg-slate-50' : 'cursor-pointer border-teal-300 bg-teal-50/60 transition hover:-translate-y-0.5 hover:shadow-sm'}`}><div><Upload className="mx-auto h-7 w-7 text-[#087A70]" /><p className="mt-2 text-sm font-black">{busy ? 'Reading Excel…' : `Upload ${title}`}</p><p className="mt-1 text-[11px] font-bold text-slate-500">.xlsx or .xls · up to 10,000 rows</p></div><input className="hidden" type="file" accept=".xlsx,.xls" disabled={disabled || busy} onChange={(event) => onSelect(source, event.target.files?.[0], event.target)} /></label>}
  </article>;
}

function Preview({ pending, busy, onClose, onConfirm }) {
  if (!pending) return null;
  return <div className="fixed inset-0 z-[160] grid place-items-center bg-slate-950/55 p-4"><div className="max-h-[90vh] w-full max-w-5xl overflow-auto rounded-2xl bg-white shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b bg-white p-5"><div><p className="text-xs font-black uppercase tracking-widest text-[#087A70]">Sales import preview</p><h5 className="mt-1 text-lg font-black">{pending.file.name} · {pending.parsed.rows.length} rows</h5></div><button type="button" onClick={onClose}><X className="h-5 w-5" /></button></div><div className="overflow-x-auto p-5"><table className="min-w-full text-left text-xs"><thead><tr>{pending.parsed.headers.map((header) => <th key={header} className="whitespace-nowrap border-b bg-slate-50 px-3 py-2 font-black">{header}</th>)}</tr></thead><tbody>{pending.parsed.preview.map((row, index) => <tr key={index}>{pending.parsed.headers.map((header) => <td key={header} className="max-w-56 truncate border-b px-3 py-2">{String(row[header] ?? '') || '-'}</td>)}</tr>)}</tbody></table></div><div className="sticky bottom-0 flex justify-end gap-2 border-t bg-white p-4"><button type="button" onClick={onClose} className="rounded-lg border px-5 py-2.5 text-sm font-black">Cancel</button><button type="button" onClick={onConfirm} disabled={busy} className="inline-flex items-center gap-2 rounded-lg bg-[#087A70] px-5 py-2.5 text-sm font-black text-white disabled:opacity-50">{busy && <Loader2 className="h-4 w-4 animate-spin" />}Confirm & import</button></div></div></div>;
}

export default function SalesDataPanel({ clientId, financialYear }) {
  const [sales, setSales] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [notice, setNotice] = useState(null); const [pending, setPending] = useState(null); const [reviewMessage, setReviewMessage] = useState(''); const [mailPreview, setMailPreview] = useState(null);
  const saveTimer = useRef(null);
  const load = useCallback(async () => { setLoading(true); try { const { data } = await api.get(API_ENDPOINTS.clients.salesData(clientId), { params: { financialYear } }); setSales(data.salesData); setNotice(null); } catch (error) { setNotice({ type: 'error', text: errorText(error) }); } finally { setLoading(false); } }, [clientId, financialYear]);
  useEffect(() => { load(); return () => clearTimeout(saveTimer.current); }, [load]);
  const saveChecklist = async (next, successText = '') => { setBusy('checklist'); try { const { data } = await api.put(API_ENDPOINTS.clients.salesChecklist(clientId), { financialYear, checklist: next.checklist, userRemarks: next.userRemarks || '' }); setSales(data.salesData); if (data.autoSubmitted) setNotice({ type: data.managerEmailSent ? 'success' : 'warning', text: data.managerEmailSent ? 'Checklist completed. Sales Data sent to Manager and email delivered.' : data.managerNotificationCreated ? 'Checklist completed. Sales Data sent to Manager with an in-app notification.' : 'Checklist completed and review is pending, but no assigned Manager was found.' }); else if (successText) setNotice({ type: 'success', text: successText }); } catch (error) { setNotice({ type: 'error', text: errorText(error) }); } finally { setBusy(''); } };
  const updateChecklistRow = (index, patch, immediate = false) => { const next = { ...sales, checklist: sales.checklist.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row) }; setSales(next); clearTimeout(saveTimer.current); if (immediate) saveChecklist(next, 'Sales checklist saved.'); else saveTimer.current = setTimeout(() => saveChecklist(next), 650); };
  const uploadProof = async (index, files) => { if (!files?.length) return; setBusy(`proof-${index}`); try { const selected = Array.from(files); const emailFiles = selected.filter((file) => /\.(eml|msg)$/i.test(file.name) || ['message/rfc822', 'application/vnd.ms-outlook'].includes(file.type)); const ordinaryFiles = selected.filter((file) => !emailFiles.includes(file)); let working = sales; for (const emailFile of emailFiles) { const form = new FormData(); form.append('file', emailFile); form.append('financialYear', financialYear); form.append('section', 'sales'); form.append('progressParticular', sales.checklist[index].particular); const { data } = await api.post(API_ENDPOINTS.clients.purchaseEmailProof(clientId), form, { headers: { 'Content-Type': 'multipart/form-data' } }); if (data.salesData) working = data.salesData; } if (ordinaryFiles.length) { const uploaded = await uploadMediaBatch(ordinaryFiles, `crm/sales-data/${clientId}/${financialYear}/proofs`); working = { ...working, checklist: working.checklist.map((row, rowIndex) => rowIndex === index ? { ...row, files: [...(row.files || []), ...uploaded].slice(0, 20) } : row) }; await saveChecklist(working); } setSales(working); setNotice({ type: 'success', text: emailFiles.length ? 'Sales email proof decoded and uploaded. Click the eye icon to open the mail.' : 'Sales checklist proof uploaded.' }); } catch (error) { if (error?.response?.data?.proof) setMailPreview(error.response.data.proof); setNotice({ type: 'error', text: errorText(error) }); } finally { setBusy(''); } };
  const removeProof = async (rowIndex, fileIndex, file) => { if (file?.proofId) { setBusy(`proof-${rowIndex}`); try { const { data } = await api.delete(API_ENDPOINTS.purchaseProofs.detail(file.proofId)); if (data.salesData) setSales(data.salesData); setNotice({ type: 'success', text: 'Sales email proof removed.' }); } catch (error) { setNotice({ type: 'error', text: errorText(error) }); } finally { setBusy(''); } return; } const next = { ...sales, checklist: sales.checklist.map((row, index) => index === rowIndex ? { ...row, files: row.files.filter((_, current) => current !== fileIndex) } : row) }; setSales(next); saveChecklist(next, 'Proof removed.'); };
  const saveEvidence = async (files) => { setBusy('evidence'); try { const { data } = await api.put(API_ENDPOINTS.clients.salesScreenshots(clientId), { financialYear, screenshots: files }); setSales(data.salesData); setNotice({ type: 'success', text: 'Sales Nil Upload evidence saved.' }); } catch (error) { setNotice({ type: 'error', text: errorText(error) }); } finally { setBusy(''); } };
  const uploadEvidence = async (files) => { if (!files?.length) return; setBusy('evidence'); try { const uploaded = await uploadMediaBatch(files, `crm/sales-data/${clientId}/${financialYear}/evidence`); await saveEvidence([...(sales.screenshots || []), ...uploaded].slice(0, 20)); } catch (error) { setNotice({ type: 'error', text: errorText(error) }); setBusy(''); } };
  const selectExcel = async (source, file, input) => { if (!file) return; setBusy(`parse-${source}`); try { setPending({ source, file, parsed: await readPurchaseWorkbook(file, source) }); } catch (error) { setNotice({ type: 'error', text: errorText(error) }); } finally { setBusy(''); if (input) input.value = ''; } };
  const confirmImport = async () => { if (!pending) return; setBusy('import'); try { const file = await uploadMedia(pending.file, `crm/sales-data/${clientId}/${financialYear}/excel`); const { data } = await api.post(API_ENDPOINTS.clients.salesImport(clientId, pending.source), { financialYear, file, rows: pending.parsed.rows, sheetName: pending.parsed.sheetName, headerRowNumber: pending.parsed.headerRowNumber }); setSales(data.salesData); setPending(null); const automaticText = data.managerEmailSent ? 'Both Sales Excel files imported. Manager review triggered and email delivered.' : data.managerNotificationCreated ? 'Both Sales Excel files imported. Manager review and in-app notification triggered; manager email could not be delivered.' : 'Both Sales Excel files imported and review status is pending, but no assigned Manager was found. Please check the user-manager mapping.'; setNotice({ type: data.autoSubmitted && !data.managerEmailSent ? 'warning' : 'success', text: data.autoSubmitted ? automaticText : 'Sales Excel validated, imported and reconciled.' }); } catch (error) { const details = error?.response?.data?.validationErrors?.slice(0, 3).map((item) => `Row ${item.rowNumber}: ${item.message}`).join(' · '); setNotice({ type: 'error', text: `${errorText(error)}${details ? ` ${details}` : ''}` }); } finally { setBusy(''); } };
  const removeImport = async (source) => { if (!window.confirm(`Remove the current Sales ${source} import? Approval status will reset.`)) return; setBusy(`remove-${source}`); try { const { data } = await api.delete(API_ENDPOINTS.clients.salesImport(clientId, source), { params: { financialYear } }); setSales(data.salesData); setNotice({ type: 'success', text: 'Sales import removed and approvals reset.' }); } catch (error) { setNotice({ type: 'error', text: errorText(error) }); } finally { setBusy(''); } };
  const submit = async () => { setBusy('submit'); try { const { data } = await api.post(API_ENDPOINTS.clients.salesSubmit(clientId), { financialYear, message: reviewMessage }); setSales(data.salesData); setNotice({ type: 'success', text: data.duplicateSubmission ? 'Already pending with Manager.' : 'Sent to Manager.' }); } catch (error) { setNotice({ type: 'error', text: `${errorText(error)} ${(error?.response?.data?.errors || []).join(' · ')}` }); } finally { setBusy(''); } };
  const review = async (stage, decision) => { if (decision === 'REJECTED' && !reviewMessage.trim()) return setNotice({ type: 'error', text: 'Rejection comments are required.' }); setBusy('review'); try { const endpoint = stage === 'manager' ? API_ENDPOINTS.clients.salesManagerReview(clientId) : API_ENDPOINTS.clients.salesComplianceReview(clientId); const { data } = await api.post(endpoint, { financialYear, decision, message: reviewMessage, acknowledgeWarnings: true }); setSales(data.salesData); setReviewMessage(''); setNotice({ type: 'success', text: `${stage === 'manager' ? 'Manager' : 'Compliance'} decision saved.` }); } catch (error) { setNotice({ type: 'error', text: errorText(error) }); } finally { setBusy(''); } };
  const totals = sales?.reconciliation?.totals || {}; const issues = sales?.reconciliation?.issues || []; const canEdit = sales?.permissions?.canEdit !== false; const uploadUnlocked = sales?.checklist?.find((row) => row.particular === 'Upload Complete')?.yesNo === 'Yes'; const nilUpload = sales?.readiness?.nilUpload;
  const progress = useMemo(() => [sales?.baseUpload, sales?.portalUpload, ['Approved', 'Rejected'].includes(sales?.managerVerificationStatus), ['Approved', 'Rejected'].includes(sales?.complianceVerificationStatus)].filter(Boolean).length * 25, [sales]);
  if (loading) return <div className="grid min-h-72 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-[#087A70]" /></div>;
  if (!sales) return <div className="m-4 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-black text-rose-700">{notice?.text || 'Sales Data could not be loaded.'}</div>;
  return <div className="space-y-4 bg-[linear-gradient(145deg,#f8fafc,#fff,#f0fdfa)] p-4">
    {notice && <div className={`flex items-start justify-between gap-3 rounded-xl border p-3 text-sm font-bold ${notice.type === 'error' ? 'border-rose-200 bg-rose-50 text-rose-700' : notice.type === 'warning' ? 'border-amber-300 bg-amber-50 text-amber-800' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}><span>{notice.text}</span><button type="button" onClick={() => setNotice(null)}><X className="h-4 w-4" /></button></div>}
    <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3 p-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#087A70]">Sales data control center</p><h5 className="mt-1 text-lg font-black">Excel reconciliation & approvals</h5><p className="mt-1 text-xs font-bold text-slate-500">Manager review starts automatically after the second successful Excel import.</p></div><div className="flex items-center gap-2"><Badge value={sales.calculatedStatus}>{sales.calculatedStatus}</Badge><button type="button" onClick={load} className="rounded-lg border p-2"><RefreshCw className="h-4 w-4" /></button></div></div><div className="h-1.5 bg-slate-100"><div className="h-full bg-gradient-to-r from-[#087A70] to-emerald-400" style={{ width: `${progress}%` }} /></div><div className="p-4"><Workflow sales={sales} /></div></div>
    <SalesUploadChecklist checklist={sales.checklist || []} canEdit={canEdit} busy={busy} onChange={updateChecklistRow} onUploadProof={uploadProof} onRemoveProof={removeProof} onPreview={setMailPreview} onError={(text) => setNotice({ type: 'error', text })} />
    {!uploadUnlocked && !nilUpload && <div className="rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm font-black text-amber-800">Set “Upload Complete” to “Yes” in the Sales checklist to unlock both Excel uploads.</div>}
    {nilUpload ? <div className="rounded-2xl border border-violet-300 bg-gradient-to-r from-violet-50 via-fuchsia-50 to-pink-50 p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h6 className="text-sm font-black text-violet-950">Sales Nil Upload path active</h6><p className="mt-1 text-xs font-bold text-violet-800">Only “Client Approval on data” is mandatory. Excel files and all other checklist validations are bypassed; extra evidence is optional.</p></div>{canEdit && <label className="cursor-pointer rounded-xl bg-violet-700 px-4 py-2.5 text-xs font-black text-white shadow-md hover:bg-violet-800">{busy === 'evidence' ? 'Uploading…' : 'Upload optional evidence'}<input type="file" multiple accept="image/*,.pdf,.eml,.msg" className="hidden" onChange={(event) => uploadEvidence(event.target.files)} /></label>}</div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(sales.screenshots || []).map((file, index) => <div key={`${file.url}-${index}`} className="flex items-center gap-2 rounded-lg border border-violet-200 bg-white p-3"><a href={file.secureUrl || file.url} target="_blank" rel="noreferrer" className="min-w-0 flex-1 truncate text-xs font-black text-violet-800 underline">{file.name}</a>{canEdit && <button type="button" aria-label={`Remove ${file.name || 'evidence'}`} onClick={() => saveEvidence(sales.screenshots.filter((_, current) => current !== index))} className="text-rose-600"><Trash2 className="h-4 w-4" /></button>}</div>)}</div></div> : <div className="grid gap-4 lg:grid-cols-2"><UploadCard source="base" upload={sales.baseUpload} disabled={!canEdit || !uploadUnlocked} busy={Boolean(busy)} financialYear={financialYear} onSelect={selectExcel} onRemove={removeImport} /><UploadCard source="portal" upload={sales.portalUpload} disabled={!canEdit || !uploadUnlocked} busy={Boolean(busy)} financialYear={financialYear} onSelect={selectExcel} onRemove={removeImport} /></div>}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric label="Base quantity" value={formatMetric(totals.baseQty)} accent="border-emerald-200 bg-emerald-50" /><Metric label="Portal quantity" value={formatMetric(totals.portalQty)} accent="border-emerald-200 bg-emerald-50" /><Metric label="Quantity diff" value={formatMetric(totals.qtyDiff)} /><Metric label="Base GST" value={formatMetric(totals.baseGst)} accent="border-orange-200 bg-orange-50" /><Metric label="Portal GST" value={formatMetric(totals.portalGst)} accent="border-orange-200 bg-orange-50" /><Metric label="GST diff" value={formatMetric(totals.gstDiff)} /></div>
    <div className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b bg-slate-50 p-3"><div><h6 className="text-sm font-black">Sales Reconciliation Review</h6><p className="text-[11px] font-bold text-slate-500">Differences remain visible to the Manager for review.</p></div><button type="button" disabled={!issues.length} onClick={() => downloadCsv(`sales-issues-${financialYear}.csv`, issues)} className="inline-flex items-center gap-1 rounded-lg border bg-white px-3 py-2 text-xs font-black disabled:opacity-40"><Download className="h-3.5 w-3.5" />CSV</button></div><div className="max-h-64 overflow-auto"><table className="w-full min-w-[850px] text-xs"><thead className="sticky top-0 bg-slate-100"><tr>{['Issue','Severity','Entity','GSTIN','Category','Material','Base Qty','Portal Qty','Difference'].map((label) => <th key={label} className="px-3 py-2 text-left">{label}</th>)}</tr></thead><tbody>{issues.map((issue, index) => <tr key={index} className="border-t"><td className="px-3 py-2 font-black">{issue.issue}</td><td><Badge value={issue.severity}>{issue.severity}</Badge></td><td>{issue.entity || '-'}</td><td>{issue.gstin || '-'}</td><td>{issue.category || '-'}</td><td>{issue.material || '-'}</td><td>{formatMetric(issue.baseQty)}</td><td>{formatMetric(issue.portalQty)}</td><td>{typeof issue.difference === 'number' ? formatMetric(issue.difference) : issue.difference || '-'}</td></tr>)}{!issues.length && <tr><td colSpan="9" className="p-6 text-center font-bold text-emerald-600"><CheckCircle2 className="mx-auto mb-2 h-5 w-5" />No reconciliation differences</td></tr>}</tbody></table></div></div>
    <div className="rounded-2xl border bg-white p-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 h-5 w-5 text-[#087A70]" /><div className="flex-1"><h6 className="text-sm font-black">Approval Workflow</h6><div className="mt-2 flex flex-wrap gap-2"><Badge value={sales.managerVerificationStatus}>Manager: {sales.managerVerificationStatus}</Badge><Badge value={sales.complianceVerificationStatus}>Compliance: {sales.complianceVerificationStatus}</Badge></div><textarea value={reviewMessage} onChange={(event) => setReviewMessage(event.target.value)} rows="2" placeholder="Submission note or rejection comments…" className="mt-3 w-full rounded-xl border p-3 text-sm font-bold" /><div className="mt-3 flex flex-wrap gap-2">{canEdit && <button type="button" onClick={submit} disabled={busy === 'submit' || !sales.readiness?.ready} className="rounded-lg bg-[#087A70] px-4 py-2.5 text-xs font-black text-white disabled:opacity-40">Submit to Manager</button>}{sales.permissions?.canManagerReview && sales.managerVerificationStatus === 'Pending' && <><button type="button" onClick={() => review('manager','APPROVED')} className="rounded-lg bg-emerald-600 px-4 py-2.5 text-xs font-black text-white">Manager Approve</button><button type="button" onClick={() => review('manager','REJECTED')} className="rounded-lg bg-rose-600 px-4 py-2.5 text-xs font-black text-white">Manager Reject</button></>}{sales.permissions?.canComplianceReview && sales.complianceVerificationStatus === 'Pending' && <><button type="button" onClick={() => review('compliance','APPROVED')} className="rounded-lg bg-emerald-600 px-4 py-2.5 text-xs font-black text-white">Compliance Approve</button><button type="button" onClick={() => review('compliance','REJECTED')} className="rounded-lg bg-rose-600 px-4 py-2.5 text-xs font-black text-white">Compliance Reject</button></>}</div>{!sales.readiness?.ready && <p className="mt-2 flex items-center gap-1 text-xs font-bold text-amber-700"><AlertTriangle className="h-3.5 w-3.5" />Upload both Sales Excel files to activate Manager review.</p>}</div></div>{!!sales.reviewHistory?.length && <div className="mt-4 border-t pt-4"><p className="mb-2 flex items-center gap-2 text-xs font-black uppercase text-slate-500"><History className="h-4 w-4" />Audit history</p>{[...sales.reviewHistory].reverse().map((item, index) => <div key={index} className="mb-2 rounded-lg bg-slate-50 px-3 py-2 text-xs font-bold"><strong>{item.stage} · {item.decision}</strong> by {item.by?.name || '-'} · {item.at ? new Date(item.at).toLocaleString('en-IN') : '-'}{item.message && <span className="mt-1 block text-slate-600">{item.message}</span>}</div>)}</div>}</div>
    <Preview pending={pending} busy={busy === 'import'} onClose={() => setPending(null)} onConfirm={confirmImport} />
    {mailPreview && <OutlookMsgViewer file={mailPreview} onClose={() => setMailPreview(null)} />}
  </div>;
}
